### ISSUE TITLE
Does not run with redux-saga@1.0.2

### ISSUE THREAD

**Issue by malcolmwhite** [jfairbank/redux-saga-test-plan#268]
redux-saga introduced some breaking changes with their move to v1.0.0. Right now I'm running into a problem where redux-saga-test-plan/lib/expectSaga/index.js tries to import from redux-saga/lib/internal/sagaHelpers. Unfortunately, it seems this file no longer exists, and I see an import failure:

```
Test suite failed to run

    Cannot find module 'redux-saga/lib/internal/sagaHelpers' from 'index.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:221:17)
      at Object.<anonymous> (node_modules/redux-saga-test-plan/lib/expectSaga/index.js:17:20)
```

**Comment by jp928** [comment]
Thanks for reporting this. I will dive into it.

**Comment by malcolmwhite** [comment]
> Thanks for reporting this. I will dive into it. In the mean time, are you working on the latest 4.0.0beta2 of this library?

I was using the 3.7, but it does work for me on 4.0.0beta. I'll use 4.0beta for now, may not be worth fixing 3.7? 

Thanks for maintaining this package, it's a great tool.

**Comment by jp928** [comment]
Thanks for using this library. I don’t have permission to release it on npm. We need to summon the Author to do it.

**Comment by malcolmwhite** [comment]
Sorry, I was unclear. I meant that if the fix is coming in 4.0, it may not be worth patching 3.7

**Comment by strider820** [comment]
@jp928 Is there some kind of ritual we need to perform to summon the author so we can release beta3 to npm?

**Comment by jp928** [comment]
@strider820 
I had informed the author via another channel. Shouldn't be long.

**Comment by jp928** [comment]
The beta3 has been released to npm. Close this issue.
